### ISSUE TITLE
Scenes do not appear

### ISSUE THREAD

**Issue by angelend** [nerohiro/nh-scenes#1]
When I create a scene it doesn't appear. I relog over and over, but they still don't seem to. There are no errors in the F8 or in the console. The script is standalone? Maybe that's why they don't appear (I don't use ESX).

**Comment by nerohiro** [comment]
Standalone means you don't need any framework to use it..

**Comment by nerohiro** [comment]
You are probably hiding the scenes which is why u can't see them, there is a keybinding for it

**Comment by angelend** [comment]
No, I press the key that I have configured to hide the scenes, but they cannot be seen. (I have already tried to change the key)

**Comment by cowardtv** [comment]
i got same issue i am creating the scene with the nh-keyboard and all and they dont appear tried restarting server nothing works

**Comment by jalenirvin** [comment]
Hey man! I love your script however, after adding it and the nh-keyboard whenever i go to place a scene the purple sphere shows up but after pressing the button again nothing happens. seems like the ui doesnt show up. do I need to add a call to the scenes? or am I missing one of your resources that makes this work? if you want proof or an easier way of talking lmk and we can discord or something c: thank you!!!

**Comment by nerohiro** [comment]
I just pulled keyboard and scenes fresh from the gits, anyone having issues is probably relating to something you are using in your framework, I suggest making sure your artifact is updated to the latest and no events are being used with the same names.
