### ISSUE TITLE
scene ui not showing up

### ISSUE THREAD

**Issue by CourageHeights** [nerohiro/nh-scenes#2]
Hey man! I love your script however, after adding it and the nh-keyboard whenever i go to place a scene the purple sphere shows up but after pressing the button again nothing happens. seems like the ui doesnt show up. do I need to add a call to the scenes? or am I missing one of your resources that makes this work? if you want proof or an easier way of talking lmk and we can discord or something c: thank you!!!

**Comment by nerohiro** [comment]
I just pulled keyboard and scenes fresh from the gits and it works on a local with no other scripts, anyone having issues is probably relating to something you are using in your framework, I suggest making sure your artifact is updated to the latest and no events are being used with the same names.
